Fix #3: add an accessor method to the currently displayed path
Skycoder42/QPathEdit pull request #4
Opened 2019-06-04 13:40 UTC by martonmiklos

This PR adds an accessor method to the currently displayed path. (It was not accessible through the QPathEdit::path() member in the case if it was invalid).

2019-06-04 14:35 UTC, Skycoder42 requested changes

2019-06-04 14:35 UTC, Skycoder42 commented on QPathEdit/qpathedit.h
> +	Q_PROPERTY(QString editPath READ editPath)
Please add a notify accessor. To do so, create the `editPathChanged` signal and emit it from `QPathEdit::updateValidInfo`

2019-06-04 21:56 UTC, martonmiklos commented on QPathEdit/qpathedit.h
> +	Q_PROPERTY(QString editPath READ editPath)
### Fixed

2019-06-05 07:33 UTC, Skycoder42 approved these changes

2019-06-05 07:33 UTC, merged